//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProduct
    {
        public long CartProductID { get; set; }
        public Nullable<long> CartID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<System.DateTime> ProductAddedDate { get; set; }
        public Nullable<System.DateTime> ProductModifiedDate { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
    }
}
