//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNominee
    {
        public int CustomerNomineeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string NomineeName { get; set; }
        public string NomineeMobile { get; set; }
        public Nullable<int> IsProfessional { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
