//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMessage
    {
        public int MessageId { get; set; }
        public long CustomerId { get; set; }
        public string Message { get; set; }
        public string MessageImage { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
