//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFriend
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long FriendCustomerId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int Status { get; set; }
    }
}
