//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMood
    {
        public int CustomerMoodId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MoodId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
