//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMessageReply
    {
        public long MessageReplyId { get; set; }
        public Nullable<long> MessageId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string ReplyMessage { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    }
}
