//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMedia
    {
        public long EventMediaId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> MediaType { get; set; }
        public string Media { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
