//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public long PartnerId { get; set; }
        public Nullable<long> OrgId { get; set; }
        public string PartnerName { get; set; }
        public string Logo { get; set; }
        public string EmailId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<long> StateId { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> PartnerTypeId { get; set; }
        public string LiveStreaming { get; set; }
        public string Mission { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
