//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripleTwo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportEmergency
    {
        public int EmergencyId { get; set; }
        public string EmergencyNumber { get; set; }
        public string EmergencyEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
